server:
  port: 8084

spring:
  application:
    name: backend-service
  profiles:
    active: @spring.profiles.active@

  sendgrid:
    apiKey: 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
    from-mail: demodev.info@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO
openapi:
  service:
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: v1.2.3
    description: Mota API service
    server: http://localhost:8084
    serverName: server test
    api-docs: This api-docs for client