server:
  port: 8084

spring:
  application:
    name: backend-service
  profiles:
    active: @spring.profiles.active@

  sendgrid:
    apiKey: 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
    from-mail: demodev.info@gmail.com
    templateId: d-fc23f47544e145768d1c8a12327fa4c6
    verificationLink: http://localhost:8080/user/confirm-email

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO
openapi:
  service:
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: v1.2.3
    description: Mota API service
    server: http://localhost:8084
    serverName: server test
    api-docs: This api-docs for client